// API Error Response Types

export interface ApiError {
  error: string
  code: string
}

// All error codes used by the API
export const ErrorCodes = {
  // Project errors
  PROJECT_NAME_INVALID: 'PROJECT_NAME_INVALID',
  PROJECT_NAME_TAKEN: 'PROJECT_NAME_TAKEN',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NOT_OWNER: 'PROJECT_NOT_OWNER',

  // Namespace errors
  NAMESPACE_INVALID: 'NAMESPACE_INVALID',

  // Visibility errors
  VISIBILITY_INVALID: 'VISIBILITY_INVALID',
  VISIBILITY_EXCEEDS_MAX: 'VISIBILITY_EXCEEDS_MAX',

  // Deploy errors
  INVALID_ZIP: 'INVALID_ZIP',
  DEPLOY_TOO_LARGE: 'DEPLOY_TOO_LARGE',
  EXTRACTED_TOO_LARGE: 'EXTRACTED_TOO_LARGE',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  INVALID_PATH: 'INVALID_PATH',
  SYMLINK_NOT_ALLOWED: 'SYMLINK_NOT_ALLOWED',
  EMPTY_DEPLOY: 'EMPTY_DEPLOY',

  // General errors
  INVALID_REQUEST: 'INVALID_REQUEST',

  // Share token errors
  SHARE_TOKENS_DISABLED: 'SHARE_TOKENS_DISABLED',
  SHARE_TOKEN_NOT_FOUND: 'SHARE_TOKEN_NOT_FOUND',
  SHARE_TOKEN_LIMIT_EXCEEDED: 'SHARE_TOKEN_LIMIT_EXCEEDED',
  SHARE_TOKEN_NAME_INVALID: 'SHARE_TOKEN_NAME_INVALID',
  SHARE_TOKEN_DURATION_INVALID: 'SHARE_TOKEN_DURATION_INVALID',
  SHARE_TOKEN_ALREADY_REVOKED: 'SHARE_TOKEN_ALREADY_REVOKED',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
