#!/usr/bin/env bun

/**
 * Reads all files from the template/ directory and generates src/template.generated.ts
 * with the templates object that can be imported at build time.
 */

import fs from 'fs/promises';
import path from 'path';

const TEMPLATE_DIR = path.join(import.meta.dir, '..', 'template');
const OUTPUT_FILE = path.join(import.meta.dir, '..', 'src', 'template.generated.ts');

// Files to skip
const SKIP_FILES = new Set(['.DS_Store']);

async function readFilesRecursively(dir: string, baseDir: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const entries = await fs.readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (SKIP_FILES.has(entry.name)) continue;

    const fullPath = path.join(dir, entry.name);
    const relativePath = path.relative(baseDir, fullPath);

    if (entry.isDirectory()) {
      const subFiles = await readFilesRecursively(fullPath, baseDir);
      Object.assign(files, subFiles);
    } else {
      const content = await fs.readFile(fullPath, 'utf-8');
      files[relativePath] = content;
    }
  }

  return files;
}

function escapeTemplateString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function main() {
  // Read all files from template directory (flat structure)
  const templates = await readFilesRecursively(TEMPLATE_DIR, TEMPLATE_DIR);

  // Generate TypeScript output
  let output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/compile-templates.ts

export const templates: Record<string, string> = {\n`;

  for (const [filePath, content] of Object.entries(templates)) {
    output += `  '${filePath}': \`${escapeTemplateString(content)}\`,\n\n`;
  }

  output += `} as const;\n`;

  await fs.writeFile(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error('Failed to compile templates:', err);
  process.exit(1);
});
