#!/usr/bin/env bun
/*
 * Regenerates the string-module assets: shared/assets/figure.svg into
 * shared/src/assets/figure-svg.generated.ts, and the comments widget
 * server/core/assets/comments-widget.js into
 * server/core/src/comments-widget.generated.ts. The module form (instead of
 * importing the sources with a Bun `with { type: "text" }` attribute) keeps
 * the publishable packages free of loader-specific syntax so their tsc-built
 * dist runs under plain Node; for the widget it also keeps a plain browser
 * script out of the Effect-boundary lint's scope, exactly like the embedded
 * renderer. Runs in the root `bun run ci`; freshness is enforced by
 * scripts/check-generated-fresh.ts.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { repoRoot } from "./workspaces";

function generateStringModule(sourcePath: string, outPath: string, exportName: string): void {
  const source = readFileSync(join(repoRoot, ...sourcePath.split("/")), "utf8");
  const out = join(repoRoot, ...outPath.split("/"));
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(
    out,
    [
      `// Generated by scripts/generate-assets.ts from ${sourcePath} — do not edit.`,
      "// Regenerate with: bun scripts/generate-assets.ts",
      `export const ${exportName}: string = ${JSON.stringify(source)};`,
      "",
    ].join("\n"),
  );
  console.log(`generated ${outPath} (${source.length} chars)`);
}

generateStringModule("shared/assets/figure.svg", "shared/src/assets/figure-svg.generated.ts", "FIGURE_SVG");
generateStringModule("server/core/assets/comments-widget.js", "server/core/src/comments-widget.generated.ts", "COMMENTS_WIDGET_JS");
