#!/usr/bin/env bun
/*
 * Regenerates shared/src/assets/figure-svg.generated.ts from
 * shared/assets/figure.svg. The module form (instead of importing the .svg
 * with a Bun `with { type: "text" }` attribute) keeps the publishable
 * packages free of loader-specific syntax so their tsc-built dist runs under
 * plain Node. Runs in the root `bun run ci`; freshness is enforced by
 * scripts/check-generated-fresh.ts.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { repoRoot } from "./workspaces";

const svg = readFileSync(join(repoRoot, "shared", "assets", "figure.svg"), "utf8");
const out = join(repoRoot, "shared", "src", "assets", "figure-svg.generated.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  [
    "// Generated by scripts/generate-assets.ts from shared/assets/figure.svg — do not edit.",
    "// Regenerate with: bun scripts/generate-assets.ts",
    `export const FIGURE_SVG: string = ${JSON.stringify(svg)};`,
    "",
  ].join("\n"),
);
console.log(`generated ${out.slice(repoRoot.length + 1)} (${svg.length} chars of svg)`);
